[package]
name = "simplerand"
version = "0.0.1"
authors = ["PumpkinSeed <qwer.kocka@gmail.com>"]
edition = "2018"
description = "Simple and fast random number generator"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PumpkinSeed/srand"
keywords = ["random"]

[dependencies]
